apiVersion: v1
kind: ServiceAccount
metadata:
  name: crondeletepod # this is service account for binding the pod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crondeletepod # This defines a role and what API it can access
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crondeletepod # This will bind the role and service account
subjects:
- kind: ServiceAccount
  name: crondeletepod
roleRef:
  kind: Role 
  name: crondeletepod
  apiGroup: rbac.authorization.k8s.io